# Generated by Django 4.1.13 on 2024-03-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texto_pesv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paso',
            new_name='PasoMongo',
        ),
        migrations.AlterModelTable(
            name='pasomongo',
            table='texto_fases',
        ),
    ]
