# Generated by Django 4.1.13 on 2024-03-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texto_pesv', '0002_rename_paso_pasomongo_alter_pasomongo_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasoMongo',
            new_name='Paso',
        ),
        migrations.AlterModelTable(
            name='paso',
            table=None,
        ),
    ]
