# Generated by Django 5.0 on 2024-01-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fase1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_pesv', models.CharField(max_length=255)),
                ('ciclo', models.CharField(max_length=255)),
                ('paso_pesv', models.CharField(max_length=255)),
                ('requisito', models.CharField(max_length=255)),
                ('criterio', models.CharField(max_length=2048)),
                ('documento_verificar', models.CharField(max_length=255)),
                ('nivel_cumplimiento', models.CharField(max_length=255)),
                ('valor_variable', models.CharField(max_length=255)),
                ('valor_obtenido', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fase1_pesv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fase2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_pesv', models.CharField(max_length=255)),
                ('ciclo', models.CharField(max_length=255)),
                ('paso_pesv', models.CharField(max_length=255)),
                ('requisito', models.CharField(max_length=255)),
                ('criterio', models.CharField(max_length=2048)),
                ('documento_verificar', models.CharField(max_length=255)),
                ('nivel_cumplimiento', models.CharField(max_length=255)),
                ('valor_variable', models.CharField(max_length=255)),
                ('valor_obtenido', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fase2_pesv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fase3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_pesv', models.CharField(max_length=255)),
                ('ciclo', models.CharField(max_length=255)),
                ('paso_pesv', models.CharField(max_length=255)),
                ('requisito', models.CharField(max_length=255)),
                ('criterio', models.CharField(max_length=2048)),
                ('documento_verificar', models.CharField(max_length=255)),
                ('nivel_cumplimiento', models.CharField(max_length=255)),
                ('valor_variable', models.CharField(max_length=255)),
                ('valor_obtenido', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fase3_pesv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fase4',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_pesv', models.CharField(max_length=255)),
                ('ciclo', models.CharField(max_length=255)),
                ('paso_pesv', models.CharField(max_length=255)),
                ('requisito', models.CharField(max_length=255)),
                ('criterio', models.CharField(max_length=2048)),
                ('documento_verificar', models.CharField(max_length=255)),
                ('nivel_cumplimiento', models.CharField(max_length=255)),
                ('valor_variable', models.CharField(max_length=255)),
                ('valor_obtenido', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fase4_pesv',
                'managed': False,
            },
        ),
    ]
