# Generated by Django 5.0 on 2024-01-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_pesv', models.CharField(max_length=255)),
                ('ciclo', models.CharField(max_length=255)),
                ('paso_pesv', models.CharField(max_length=255)),
                ('requisito', models.CharField(max_length=255)),
                ('criterio', models.CharField(max_length=2048)),
                ('documento_verificar', models.CharField(max_length=255)),
                ('nivel_cumplimiento', models.CharField(max_length=255)),
                ('valor_variable', models.CharField(max_length=255)),
                ('valor_obtenido', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='fase1',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fase2',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fase3',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fase4',
            options={},
        ),
    ]
