# Generated by Django 4.1.13 on 2024-03-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flota_vehiculos',
            fields=[
                ('id_flota_vehiculos', models.AutoField(primary_key=True, serialize=False)),
                ('numero_motocicletas_patinetas_propios', models.CharField(max_length=255)),
                ('numero_motocicletas_patinetas_terceros', models.CharField(max_length=255)),
                ('numero_vehiculos_livianos_propios', models.CharField(max_length=255)),
                ('numero_vehiculos_livianos_terceros', models.CharField(max_length=255)),
                ('numero_vehiculos_pesados_propios', models.CharField(max_length=255)),
                ('numero_vehiculos_pesados_terceros', models.CharField(max_length=255)),
                ('numero_vehiculos_furgon_propios', models.CharField(max_length=255)),
                ('numero_vehiculos_furgon_terceros', models.CharField(max_length=255)),
                ('numero_vehiculos_carga_propios', models.CharField(max_length=255)),
                ('numero_vehiculos_carga_terceros', models.CharField(max_length=255)),
                ('numero_maquinaria_amarilla_propios', models.CharField(max_length=255)),
                ('numero_maquinaria_amarilla_terceros', models.CharField(max_length=255)),
                ('numero_vehiculos_no_automotores_propios', models.CharField(max_length=255)),
                ('numero_vehiculos_no_automotores_terceros', models.CharField(max_length=255)),
                ('total_vehiculos', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'flota_vehiculos_caracterizacion',
                'managed': False,
            },
        ),
    ]
