# Generated by Django 4.1.13 on 2024-03-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('nit_empresa', models.CharField(max_length=255)),
                ('actividades_CIIU', models.CharField(max_length=255)),
                ('tamano_empresa', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('segmento_perteneciente', models.CharField(max_length=255)),
                ('contacto_cargo', models.CharField(max_length=255)),
                ('certificaciones_adquiridas', models.CharField(max_length=255)),
                ('dx_realizados', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
    ]
