# Generated by Django 4.1.13 on 2024-03-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas_conductores',
            fields=[
                ('id_personas', models.AutoField(primary_key=True, serialize=False)),
                ('trabajadores_directos_conductores', models.CharField(max_length=255)),
                ('trabajadores_adminsitrativos_conductores', models.CharField(max_length=255)),
                ('contratistas_conductores', models.CharField(max_length=255)),
                ('personal_tercerizacion_conductores', models.CharField(max_length=255)),
                ('otros_conductores', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'personas_conducen_caracterizacion',
                'managed': False,
            },
        ),
    ]
